Initial classes
Dhii/data-state-base pull request #1
Opened 2018-07-06 15:46 UTC by mecha

2018-07-13 09:44 UTC, XedinUnknown requested changes

2018-07-13 09:44 UTC, XedinUnknown commented on src/Exception/AbstractBaseTransitionerException.php
> +abstract class AbstractBaseTransitionerException extends RootException implements TransitionerExceptionInterface
Consider extending [`AbstractBaseException`].

[`AbstractBaseException`]: https://github.com/Dhii/exception/blob/develop/src/AbstractBaseException.php#L7

2018-07-13 09:44 UTC, XedinUnknown commented on src/Exception/TransitionerException.php
> +     * @param int|null                   $code         The error code, if any.
The [`InitBaseExceptionCapableTrait`][] should probably be used as a standard for what arguments and types an exception should accept.

[`InitBaseExceptionCapableTrait`]: https://github.com/Dhii/exception/blob/develop/src/InitBaseExceptionCapableTrait.php#L27

2018-07-13 14:04 UTC, mecha commented on src/Exception/TransitionerException.php
> +     * @param int|null                   $code         The error code, if any.
[`InitBaseExceptionCapableTrait`](https://github.com/Dhii/exception/blob/develop/src/InitBaseExceptionCapableTrait.php#L27) is part of [`ExceptionTrait`](https://github.com/Dhii/exception/blob/develop/src/ExceptionTrait.php), which is `use`d by [`AbstractBaseException`](https://github.com/Dhii/exception/blob/develop/src/AbstractBaseException.php#L7). The abstract base exception in this package now extends that, so it's being used indirectly through inheritance.

2018-07-13 14:23 UTC, XedinUnknown commented on src/Exception/TransitionerException.php
> +     * @param int|null                   $code         The error code, if any.
That's true. And yet, the documented types haven't changed.

2018-07-13 14:24 UTC, XedinUnknown requested changes

2018-07-13 14:24 UTC, XedinUnknown commented on src/Exception/CouldNotTransitionException.php
> +    protected function _setTransition($transition)
Looks like awareness can very easily be extracted into traits and put into [dhii/data-state-abstract][].

[dhii/data-state-abstract]: https://github.com/Dhii/data-state-abstract

2018-07-13 14:28 UTC, mecha commented on src/Exception/TransitionerException.php
> +     * @param int|null                   $code         The error code, if any.
My bad. I didn't interpret your first message as meaning to use the same docs as that trait, but merely to `use` the it. Will correct.

2018-07-19 16:29 UTC, XedinUnknown approved these changes

2018-07-19 16:29 UTC, merged